{
 "title": "Data & Database Health",
 "tags": [
  "production",
  "database"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(supabase_usage_metrics_user_queries_total,job)"
    }
   },
   {
    "name": "project",
    "label": "Project Ref",
    "query": {
     "query": "label_values({job=~\"$job\"},supabase_project_ref)"
    }
   },
   {
    "name": "supabase_identifier",
    "label": "Supabase Identifier",
    "query": {
     "query": "label_values({job=~\"$job\"},supabase_identifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "x": 0, "y": 6, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  100 - (\r\n    avg(\r\n      rate(\r\n        node_cpu_seconds_total{\r\n          mode=\"idle\",\r\n          job=\"integrations/supabase/3549404-metrics-endpoint-dropleather-supabase-production\",\r\n          supabase_project_ref=\"kvnspvbieacjhwlckpla\",\r\n          supabase_identifier=\"kvnspvbieacjhwlckpla\"\r\n        }[5m]\r\n      )\r\n    ) by (instance) * 100\r\n  ),\r\n  0\r\n)"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "x": 8, "y": 6, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"} - node_memory_MemFree_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"} - node_memory_Buffers_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"} - node_memory_Cached_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}) / node_memory_MemTotal_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}) * 100\n\n"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "x": 16, "y": 6, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "x": 0, "y": 14, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "x": 8, "y": 14, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"} - node_memory_MemFree_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"} - (node_memory_Cached_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"} + node_memory_Buffers_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"} + node_memory_Buffers_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"} - node_memory_SwapFree_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Filesystem used (including data)",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "x": 16, "y": 14, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\",device!~'rootfs'})",
     "legendFormat": "Disk mounted at {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Database size ",
   "type": "timeseries",
   "description": "Disk space used by the database",
   "gridPos": { "x": 0, "y": 22, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_mb{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}",
     "legendFormat": "Database size"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "timeseries",
   "description": "Active number of client connections",
   "gridPos": { "x": 8, "y": 22, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_database_num_backends{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}",
     "legendFormat": "postgres connections"
    },
    {
     "expr": "pgbouncer_used_clients{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}",
     "legendFormat": "pgbouncer connections"
    },
    {
     "expr": "sum by (Name) (pgbouncer_pools_client_waiting_connections{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"})",
     "legendFormat": "pgbouncer client connections waiting"
    }
   ]
  },
  {
   "title": "Postgres status",
   "type": "stat",
   "gridPos": { "x": 16, "y": 22, "w": 8, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}"
    }
   ]
  },
  {
   "title": "pgbouncer status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 30, "w": 8, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_up{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}"
    }
   ]
  },
  {
   "title": "Query throughput and execution time",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 30, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(supabase_usage_metrics_user_queries_total{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])",
     "legendFormat": "No. of user queries"
    },
    {
     "expr": "rate(pg_stat_statements_total_queries{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])",
     "legendFormat": "Total no. of queries"
    },
    {
     "expr": "rate(pg_stat_statements_total_time_seconds{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])",
     "legendFormat": "Total time spent"
    }
   ]
  },
  {
   "title": "pg stats",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 30, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit_total{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])",
     "legendFormat": "Tx committed"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback_total{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])",
     "legendFormat": "Tx rolled back"
    },
    {
     "expr": "rate(pg_stat_database_deadlocks_total{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}[$__rate_interval])",
     "legendFormat": "Deadlocks detected"
    }
   ]
  },
  {
   "title": "Realtime replication status",
   "type": "stat",
   "description": "Realtime replication status",
   "gridPos": { "x": 0, "y": 38, "w": 8, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "replication_realtime_slot_status{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}"
    }
   ]
  },
  {
   "title": "Realtime replication lag",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 38, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "replication_realtime_lag_bytes{job=~\"$job\", supabase_project_ref=\"$project\", supabase_identifier=~\"${supabase_identifier:pipe}\"}",
     "legendFormat": "Replication lag "
    }
   ]
  },
  {
   "title": "Long-running transaction",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_activity_xact_runtime{job=\"integrations/supabase/3549404-metrics-endpoint-dropleather-supabase-production\",supabase_project_ref=\"kvnspvbieacjhwlckpla\",supabase_identifier=\"kvnspvbieacjhwlckpla\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks — 15m",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(pg_stat_database_deadlocks_total{job=\"integrations/supabase/3549404-metrics-endpoint-dropleather-supabase-production\",supabase_project_ref=\"kvnspvbieacjhwlckpla\",supabase_identifier=\"kvnspvbieacjhwlckpla\"}[15m]))) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data filesystem used",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(100*(1-(node_filesystem_avail_bytes{mountpoint=\"/data\",fstype!=\"rootfs\",job=\"integrations/supabase/3549404-metrics-endpoint-dropleather-supabase-production\",supabase_project_ref=\"kvnspvbieacjhwlckpla\",supabase_identifier=\"kvnspvbieacjhwlckpla\"}/node_filesystem_size_bytes{mountpoint=\"/data\",fstype!=\"rootfs\",job=\"integrations/supabase/3549404-metrics-endpoint-dropleather-supabase-production\",supabase_project_ref=\"kvnspvbieacjhwlckpla\",supabase_identifier=\"kvnspvbieacjhwlckpla\"})))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}